print('******************')
print('CALCULADORA DE IMC')
print('******************')

peso = float(input('Digite seu peso: '))
altura = float(input('Digite sua altura: '))
indiceMC = peso / (altura * altura)
print('-----------------')
print('Seu IMC é {:.2f}'.format(indiceMC))
print('-----------------')